### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by ameershah48** [zulfajuniadi/jadual-sekolah#1]
Great app! But when trying to reset the password, I get this error.
Also, maybe change the APP_ENV to production to avoid displaying sensitive data :)

![image](https://user-images.githubusercontent.com/51684075/105662489-cdae5c80-5f0a-11eb-84b8-0c1b60974c75.png)

**Comment by zulfajuniadi** [comment]
Fixed, configured email out via mailgun.

**Comment by ameershah48** [comment]
Terbaik!
