### ISSUE TITLE
Fungsi Import & Export jadual / Kongsi Jadual

### ISSUE THREAD

**Issue by harith-a** [zulfajuniadi/jadual-sekolah#3]
Nampak ada cadangan di twitter untuk fungsi berkongsi jadual. Kalau ada masa saya cuba bantu, tapi saya letak di sini untuk tengok sejauh mana permintaan terhadap feature ini.

**Comment by zulfajuniadi** [comment]
Ingat flow dia is:
1) Untuk pengeksport: pilih anak > export jadual
2) Untuk pengimport: pilih snak > import jadual

**Comment by ameershah48** [comment]
saya ada buat pr untuk fungsi import jadual, harap dapat membantu dan mungkin boleh di tambah baik 💯

**Comment by zulfajuniadi** [comment]
PR merged and deployed. Terima kasih. :)
